FROM node:16

WORKDIR /app/server

COPY package*.json ./

COPY prisma ./prisma/

COPY .env ./

COPY tsconfig.json ./

COPY . .

RUN npm ci

RUN npx prisma generate

RUN npx prisma migrate deploy

RUN npx prisma db seed

EXPOSE 4000 

CMD ["npm", "run", "e2e"]