import {
  Adviser,
  Mentor,
  Project,
  Student,
  Submission,
  User,
} from "@prisma/client";

/**
 * Contains data for testing the dashboard admin testing
 */
export const MOCK_SUBMISSION = {
  cohortYear: 2025,
  dropped: "false",
};

export const MOCK_USER_1 = {
  id: 1,
  name: "Student",
  email: "student@skylab.com",
  profilePicUrl: "https://loremflickr.com/640/480",
  githubUrl: "http://profitable-revelation.org",
  linkedinUrl: "https://important-software.org",
  personalSiteUrl: "http://wretched-macadamia.net",
  selfIntro: "Amet nihil sunt.",
  password: "password",
  submitterId: null,
  userId: 1,
  projectId: 1,
  nusnetId: "e0945921",
  matricNo: "A0283666L",
  cohortYear: 2025,
} as User & Student;

export const MOCK_USER_2 = {
  id: 2,
  name: "Edd Lynch",
  email: "Edd17@yahoo.com",
  profilePicUrl: "https://loremflickr.com/640/480",
  githubUrl: "https://imaginative-wild.com",
  linkedinUrl: "http://extroverted-mycoplasma.com",
  personalSiteUrl: "https://probable-patrol.net",
  selfIntro: "Blanditiis nulla perspiciatis neque recusandae ab sed.",
  submitterId: null,
  password: "password1",
  userId: 400,
  projectId: 1,
  nusnetId: "e0594263",
  matricNo: "A0870763V",
  cohortYear: 2025,
} as User & Student;

export const MOCK_USER_3 = {
  id: 3,
  name: "Explorer",
  email: "Explorer@gmail.com",
  profilePicUrl: "https://loremflickr.com/640/480",
  githubUrl: "http://space-explorer.github.com",
  linkedinUrl: "https://space-explorer-linkedin.com",
  personalSiteUrl: "http://deep-space-adventures.com",
  selfIntro: "Preparing for a Mars expedition.",
  password: "password2",
  submitterId: null,
  userId: 127,
  projectId: 127,
  nusnetId: "e0456789",
  matricNo: "A0456789B",
  cohortYear: 2025,
} as User & Student;

export const MOCK_USER_4 = {
  id: 4,
  name: "Lunar Explorer",
  email: "LunarExplorer@gmail.com",
  profilePicUrl: "https://loremflickr.com/640/480",
  githubUrl: "http://lunar-exploration.github.com",
  linkedinUrl: "https://lunar-explorer-linkedin.com",
  personalSiteUrl: "http://lunar-adventure.com",
  selfIntro: "Exploring the moon for humanity.",
  password: "password3",
  submitterId: null,
  userId: 160,
  projectId: 160,
  nusnetId: "e0654321",
  matricNo: "A0654321Z",
  cohortYear: 2025,
} as User & Student;

export const MOCK_USER_5 = {
  id: 5,
  name: "Joshua Taylor",
  email: "JoshuaTaylor@gmail.com",
  profilePicUrl: "https://loremflickr.com/640/480",
  githubUrl: "https://moonbase.com",
  linkedinUrl: "http://space-exploration.org",
  personalSiteUrl: "https://explore-space.net",
  selfIntro: "Working towards new space frontiers.",
  password: "password4",
  submitterId: null,
  userId: 150,
  projectId: 150,
  nusnetId: "e0674359",
  matricNo: "A0587102P",
  cohortYear: 2025,
} as User & Student;

export const MOCK_PROJECT_WITH_SUBMISSION = {
  fromProject: {
    achievement: "Vostok",
    adviser: {
      id: 1,
      userId: 403,
      nusnetId: "e0353060",
      matricNo: "A0434950A",
      cohortYear: 2025,
      name: "Adviser",
      email: "adviser@skylab.com",
      profilePicUrl: "https://loremflickr.com/640/480",
      githubUrl: "https://kindhearted-worship.com",
      linkedinUrl: "http://broken-beard.com",
      personalSiteUrl: "http://corrupt-clavicle.info",
      selfIntro: "Quasi facilis dolorum sequi ipsum.",
      submitterId: null,
    } as Adviser,
    mentor: {
      name: "Mentor",
      email: "mentor@skylab.com",
      profilePicUrl: "https://loremflickr.com/640/480",
      githubUrl: "https://complicated-stamen.info",
      linkedinUrl: "http://decent-story.org",
      personalSiteUrl: "http://fussy-teenager.info",
      selfIntro: "Illo asperiores quis esse soluta ut molestias vero.",
      submitterId: null,
      id: 1,
      userId: 503,
      cohortYear: 2025,
    } as Mentor,
    id: 1,
    name: "grizzled cheddar",
    teamName: "Team worthy redirect",
    adviserId: 1,
    mentorId: 1,
    cohortYear: 2025,
    proposalPdf: "http://cute-stall.org",
    posterUrl: "https://loremflickr.com/640/480",
    videoUrl: null,
    hasDropped: false,
    students: [MOCK_USER_1, MOCK_USER_2] as (User & Student)[],
  } as Project,
  submission: [
    {
      id: 1,
      updatedAt: new Date("2025-02-01T05:30:08.436Z"),
      deadlineId: 1,
      isDraft: false,
      fromUserId: 1,
      toUserId: 2,
      fromProjectId: 1,
      toProjectId: 1,
    },
    {
      id: 2,
      updatedAt: new Date("2025-02-01T05:30:08.443Z"),
      deadlineId: 2,
      isDraft: false,
      fromUserId: 1,
      toUserId: 2,
      fromProjectId: 1,
      toProjectId: 1,
    },
  ] as Submission[],
};

export const MOCK_PROJECT_WITHOUT_SUBMISSION = {
  fromProject: {
    achievement: "Vostok",
    adviser: {
      id: 2,
      userId: 403,
      nusnetId: "e0353060",
      matricNo: "A0434950A",
      cohortYear: 2025,
      name: "Adviser",
      email: "adviser@skylab.com",
      profilePicUrl: "https://loremflickr.com/640/480",
      githubUrl: "https://kindhearted-worship.com",
      linkedinUrl: "http://broken-beard.com",
      personalSiteUrl: "http://corrupt-clavicle.info",
      selfIntro: "Quasi facilis dolorum sequi ipsum.",
      submitterId: null,
    } as Adviser,
    mentor: {
      name: "Mentor",
      email: "mentor@skylab.com",
      profilePicUrl: "https://loremflickr.com/640/480",
      githubUrl: "https://complicated-stamen.info",
      linkedinUrl: "http://decent-story.org",
      personalSiteUrl: "http://fussy-teenager.info",
      selfIntro: "Illo asperiores quis esse soluta ut molestias vero.",
      submitterId: null,
      id: 2,
      userId: 503,
      cohortYear: 2025,
    } as Mentor,
    id: 2,
    name: "potato chicken",
    teamName: "Team apollo",
    adviserId: 2,
    mentorId: 2,
    cohortYear: 2025,
    proposalPdf: "http://cute-stall.org",
    posterUrl: "https://loremflickr.com/640/480",
    videoUrl: null,
    hasDropped: false,
    students: [MOCK_USER_3, MOCK_USER_4],
  } as Project,
  submission: [] as Submission[],
};

export const MOCK_PROJECT_DROPPED = {
  fromProject: {
    achievement: "Vostok",
    adviser: {
      id: 2,
      userId: 403,
      nusnetId: "e0353060",
      matricNo: "A0434950A",
      cohortYear: 2025,
      name: "Adviser",
      email: "adviser@skylab.com",
      profilePicUrl: "https://loremflickr.com/640/480",
      githubUrl: "https://kindhearted-worship.com",
      linkedinUrl: "http://broken-beard.com",
      personalSiteUrl: "http://corrupt-clavicle.info",
      selfIntro: "Quasi facilis dolorum sequi ipsum.",
      submitterId: null,
    } as Adviser,
    mentor: {
      name: "Mentor",
      email: "mentor@skylab.com",
      profilePicUrl: "https://loremflickr.com/640/480",
      githubUrl: "https://complicated-stamen.info",
      linkedinUrl: "http://decent-story.org",
      personalSiteUrl: "http://fussy-teenager.info",
      selfIntro: "Illo asperiores quis esse soluta ut molestias vero.",
      submitterId: null,
      id: 2,
      userId: 503,
      cohortYear: 2025,
    } as Mentor,
    id: 2,
    name: "potato chicken",
    teamName: "Team apollo",
    adviserId: 2,
    mentorId: 2,
    cohortYear: 2025,
    proposalPdf: "http://cute-stall.org",
    posterUrl: "https://loremflickr.com/640/480",
    videoUrl: null,
    hasDropped: true,
    students: [MOCK_USER_3, MOCK_USER_4],
  } as Project,
  submission: [] as Submission[],
};

export const MOCK_DEADLINES = [
  {
    id: 1,
    name: "Milestone 1",
    cohortYear: 2025,
    createdOn: new Date("2025-02-01T05:30:08.407Z"),
    dueBy: new Date("2025-02-01T05:30:08.407Z"),
    desc: null,
    type: "Milestone",
    updatedAt: new Date("2025-02-01T05:30:08.407Z"),
    evaluatingMilestoneId: null,
    evaluating: null,
  },
  {
    id: 2,
    name: "Milestone 2",
    cohortYear: 2025,
    createdOn: new Date("2025-02-01T05:30:08.407Z"),
    dueBy: new Date("2025-02-01T05:30:08.407Z"),
    desc: null,
    type: "Milestone",
    updatedAt: new Date("2025-02-01T05:30:08.407Z"),
    evaluatingMilestoneId: null,
    evaluating: null,
  },
  {
    id: 3,
    name: "Milestone 3",
    cohortYear: 2025,
    createdOn: new Date("2025-02-01T05:30:08.407Z"),
    dueBy: new Date("2025-02-01T05:30:08.407Z"),
    desc: null,
    type: "Milestone",
    updatedAt: new Date("2025-02-01T05:30:08.407Z"),
    evaluatingMilestoneId: null,
    evaluating: null,
  },
];

export const MOCK_FLATTENED_PROJECT = {
  adviser: {
    id: 20,
    userId: 422,
    nusnetId: "e0691867",
    matricNo: "A0079877A",
    cohortYear: 2025,
    name: "Rachael Gleason",
    email: "Rachael.Gleason208@hotmail.com",
    profilePicUrl: "https://loremflickr.com/640/480",
    githubUrl: "https://late-nutmeg.org",
    linkedinUrl: "http://celebrated-vampire.info",
    personalSiteUrl: "http://crazy-clue.info",
    selfIntro: "Repudiandae et pariatur accusantium reprehenderit eum eum non.",
    submitterId: null,
  },
  mentor: {
    name: "Tyree Brakus",
    email: "Tyree.Brakus20@yahoo.com",
    profilePicUrl: "https://loremflickr.com/640/480",
    githubUrl: "http://bumpy-monitor.info",
    linkedinUrl: "http://warm-order.com",
    personalSiteUrl: "https://fearful-inscription.net",
    selfIntro: "Odit nulla at quisquam consequuntur et.",
    submitterId: null,
    id: 20,
    userId: 522,
    cohortYear: 2025,
  },
  id: 20,
  name: "tired theory",
  teamName: "Team naive heir",
  adviserId: 20,
  mentorId: 20,
  achievement: "Gemini",
  cohortYear: 2025,
  proposalPdf: "http://loathsome-regionalism.info",
  posterUrl: "https://loremflickr.com/640/480",
  videoUrl: null,
  hasDropped: false,
  students: [
    {
      name: "Destiny Hills",
      email: "Destiny.Hills1989@gmail.com",
      profilePicUrl: "https://loremflickr.com/640/480",
      githubUrl: "https://trusting-preparation.info",
      linkedinUrl: "http://adorable-messy.name",
      personalSiteUrl: "http://beloved-atm.net",
      selfIntro: "Repudiandae cupiditate voluptatum sit tempora recusandae.",
      submitterId: null,
      id: 20,
      userId: 20,
      projectId: 20,
      nusnetId: "e0619472",
      matricNo: "A0379322P",
      cohortYear: 2025,
    },
    {
      name: "Arno Bernier",
      email: "Arno.Bernier38088@hotmail.com",
      profilePicUrl: "https://loremflickr.com/640/480",
      githubUrl: "https://crooked-luggage.info",
      linkedinUrl: "https://functional-sunroom.name",
      personalSiteUrl: "https://strict-thing.org",
      selfIntro: "Rem deserunt et aut commodi cupiditate.",
      submitterId: null,
      id: 381,
      userId: 381,
      projectId: 20,
      nusnetId: "e0512234",
      matricNo: "A0114853A",
      cohortYear: 2025,
    },
  ],
};
